####################$
# cfgs for cifar10 #
####################$

# args for network
net_avgpool_size: 3
net_heads:
  - 70
  - 10

# args for dataset and dataloader
dataset: cifar10
data_root: /home/xidian_yangxu/dzy/dc/cifar10/
tfm_means: (0.5071, 0.4866, 0.4409)
tfm_stds: (0.2009, 0.1984, 0.2023)
tfm_size: (32, 32)
tfm_resize: 40

batch_size: 50