##################
# cfgs for imagenet10 #
##################

# args for network
net_avgpool_size: 7
net_heads:
  - 70
  - 15

# args for dataset and dataloader
dataset: imagenet10
data_root: /home/xidian_yangxu/dzy/dc/imagenetdog/
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (96, 96)
tfm_resize: 112

# smaller batch size for lower memory consumption
batch_size: 60
