##################
# cfgs for Tiny #
##################

# args for network
net_avgpool_size: 5
net_heads:
  - 700
  - 200

# args for dataset and dataloader
dataset: tinyimagenet
data_root: /home/xidian_yangxu/dzy/dc/tiny/tiny-imagenet-200/train/
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (64, 64)
tfm_resize: 80

# smaller batch size for lower memory consumption
batch_size: 300
